// User Module
const GET_USERS_DATA_INIT = "GET_USERS_DATA_INIT";
const GET_USERS_DATA_SUCCESS = "GET_USERS_DATA_SUCCESS";
const GET_USERS_DATA_ERROR = "GET_USERS_DATA_ERROR";

const GET_USERS_DEPARTMENTS_INIT = "GET_USERS_DEPARTMENTS_INIT";
const GET_USERS_DEPARTMENTS_SUCCESS = "GET_USERS_DEPARTMENTS_SUCCESS";
const GET_USERS_DEPARTMENTS_ERROR = "GET_USERS_DEPARTMENTS_ERROR";

const ADD_USERS_DATA_INIT = "ADD_USERS_DATA_INIT";
const ADD_USERS_DATA_SUCCESS = "ADD_USERS_DATA_SUCCESS";
const ADD_USERS_DATA_ERROR = "ADD_USERS_DATA_ERROR";

const EDIT_USERS_INIT = "EDIT_USERS_INIT";
const EDIT_USERS_SUCCESS = "EDIT_USERS_SUCCESS";
const EDIT_USERS_ERROR = "EDIT_USERS_ERROR";

const GET_USERS_PERMISSION_INIT = "GET_USERS_PERMISSION_INIT";
const GET_USERS_PERMISSION_SUCCESS = "GET_USERS_PERMISSION_SUCCESS";
const GET_USERS_PERMISSION_ERROR = "GET_USERS_PERMISSION_ERROR";

const UPDATE_USERS_INIT = "UPDATE_USERS_INIT";
const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
const UPDATE_USERS_ERROR = "UPDATE_USERS_ERROR";

// Department Module
const GET_DEPARTMENTS_INIT = "GET_DEPARTMENTS_INIT";
const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
const GET_DEPARTMENTS_ERROR = "GET_DEPARTMENTS_ERROR";

const ADD_DEPARTMENTS_INIT = "ADD_DEPARTMENTS_INIT";
const ADD_DEPARTMENTS_SUCCESS = "ADD_DEPARTMENTS_SUCCESS";
const ADD_DEPARTMENTS_ERROR = "ADD_DEPARTMENTS_ERROR";

const GET_DEPARTMENTS_BY_ID_INIT = "GET_DEPARTMENTS_BY_ID_INIT";
const GET_DEPARTMENTS_BY_ID_SUCCESS = "GET_DEPARTMENTS_BY_ID_SUCCESS";
const GET_DEPARTMENTS_BY_ID_ERROR = "GET_DEPARTMENTS_BY_ID_ERROR";

const EDIT_DEPARTMENTS_INIT = "EDIT_DEPARTMENTS_INIT";
const EDIT_DEPARTMENTS_SUCCESS = "EDIT_DEPARTMENTS_SUCCESS";
const EDIT_DEPARTMENTS_ERROR = "EDIT_DEPARTMENTS_ERROR";

// Performance Main Parameter
const GET_PERFORMANCE_INIT = "GET_PERFORMANCE_INIT";
const GET_PERFORMANCE_SUCCESS = "GET_PERFORMANCE_SUCCESS";
const GET_PERFORMANCE_ERROR = "GET_PERFORMANCE_ERROR";

const ADD_PERFORMANCE_INIT = "ADD_PERFORMANCE_INIT";
const ADD_PERFORMANCE_SUCCESS = "ADD_PERFORMANCE_SUCCESS";
const ADD_PERFORMANCE_ERROR = "ADD_PERFORMANCE_ERROR";

const GET_PERFORMANCE_BY_ID_INIT = "GET_PERFORMANCE_BY_ID_INIT";
const GET_PERFORMANCE_BY_ID_SUCCESS = "GET_PERFORMANCE_BY_ID_SUCCESS";
const GET_PERFORMANCE_BY_ID_ERROR = "GET_PERFORMANCE_BY_ID_ERROR";

const EDIT_PERFORMANCE_INIT = "EDIT_PERFORMANCE_INIT";
const EDIT_PERFORMANCE_SUCCESS = "EDIT_PERFORMANCE_SUCCESS";
const EDIT_PERFORMANCE_ERROR = "EDIT_PERFORMANCE_ERROR";

// Sub Performance
const GET_SUBPERFORMANCE_INIT = "GET_SUBPERFORMANCE_INIT";
const GET_SUBPERFORMANCE_SUCCESS = "GET_SUBPERFORMANCE_SUCCESS";
const GET_SUBPERFORMANCE_ERROR = "GET_SUBPERFORMANCE_ERROR";

const ADD_SUBPERFORMANCE_INIT = "ADD_SUBPERFORMANCE_INIT";
const ADD_SUBPERFORMANCE_SUCCESS = "ADD_SUBPERFORMANCE_SUCCESS";
const ADD_SUBPERFORMANCE_ERROR = "ADD_SUBPERFORMANCE_ERROR";

const EDIT_SUBPERFORMANCE_INIT = "EDIT_SUBPERFORMANCE_INIT";
const EDIT_SUBPERFORMANCE_SUCCESS = "EDIT_SUBPERFORMANCE_SUCCESS";
const EDIT_SUBPERFORMANCE_ERROR = "EDIT_SUBPERFORMANCE_ERROR";

const GET_SUBPERFORMANCE_BY_ID_INIT = "GET_SUBPERFORMANCE_BY_ID_INIT";
const GET_SUBPERFORMANCE_BY_ID_SUCCESS = "GET_SUBPERFORMANCE_BY_ID_SUCCESS";
const GET_SUBPERFORMANCE_BY_ID_ERROR = "GET_SUBPERFORMANCE_BY_ID_ERROR";

// Evaluation
const GET_CALCULATION_INIT = "GET_PERFORMANCE_ID_INIT";
const GET_CALCULATION_SUCCESS = "GET_PERFORMANCE_ID_SUCCESS";
const GET_CALCULATION_ERROR = "GET_PERFORMANCE_ID_ERROR";

const SAVE_CALCULATION_INIT = "SAVE_PERFORMANCE_ID_INIT";
const SAVE_CALCULATION_SUCCESS = "SAVE_PERFORMANCE_ID_SUCCESS";
const SAVE_CALCULATION_ERROR = "SAVE_PERFORMANCE_ID_ERROR";

// Mom Modules
const GET_MOM_INIT = "GET_MOM_INIT";
const GET_MOM_SUCCESS = "GET_MOM_SUCCESS";
const GET_MOM_ERROR = "GET_MOM_ERROR";

const SUBMIT_MOM_INIT = "SUBMIT_MOM_INIT";
const SUBMIT_MOM_SUCCESS = "SUBMIT_MOM_SUCCESS";
const SUBMIT_MOM_ERROR = "SUBMIT_MOM_ERROR";

const EDIT_MOM_DATA_INIT = "EDIT_MOM_DATA_INIT";
const EDIT_MOM_DATA_SUCCESS = "EDIT_MOM_DATA_SUCCESS";
const EDIT_MOM_DATA_ERROR = "EDIT_MOM_DATA_ERROR";

// Time Log
const ADD_CHECKIN_INIT = "ADD_CHECKIN_INIT";
const ADD_CHECKIN_SUCCESS = "ADD_CHECKIN_SUCCESS";
const ADD_CHECKIN_ERROR = "ADD_CHECKIN_ERROR";

const UPDATE_CHECKOUT_INIT = "UPDATE_CHECKOUT_INIT";
const UPDATE_CHECKOUT_SUCCESS = "UPDATE_CHECKOUT_SUCCESS";
const UPDATE_CHECKOUT_ERROR = "UPDATE_CHECKOUT_ERROR";

// Sales Module
const PROPOSAL_SUBMISSION_INIT = "PROPOSAL_SUBMISSION_INIT";
const PROPOSAL_SUBMISSION_SUCCESS = "PROPOSAL_SUBMISSION_SUCCESS";
const PROPOSAL_SUBMISSION_ERROR = "PROPOSAL_SUBMISSION_ERROR";

const POST_PROPOSAL_SUBMIT_INIT = "POST_PROPOSAL_SUBMIT_INIT";
const POST_PROPOSAL_SUBMIT_SUCCESS = "POST_PROPOSAL_SUBMIT_SUCCESS";
const POST_PROPOSAL_SUBMIT_ERROR = "POST_PROPOSAL_SUBMIT_ERROR";

const GET_PROPOSAL_BY_ID_INIT = "GET_PROPOSAL_BY_ID_INIT";
const GET_PROPOSAL_BY_ID_SUCCESS = "GET_PROPOSAL_BY_ID_SUCCESS";
const GET_PROPOSAL_BY_ID_ERROR = "GET_PROPOSAL_BY_ID_ERROR";

const UPLOAD_PROPOSAL_INIT = "UPLOAD_PROPOSAL_INIT";
const UPLOAD_PROPOSAL_SUCCESS = "UPLOAD_PROPOSAL_SUCCESS";
const UPLOAD_PROPOSAL_ERROR = "UPLOAD_PROPOSAL_ERROR";

const UPDATE_STATUS_INIT = "UPDATE_STATUS_INIT";
const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR";

const GET_SALES_DROPDOWN_INIT = "GET_SALES_DROPDOWN_INIT";
const GET_SALES_DROPDOWN_SUCCESS = "GET_SALES_DROPDOWN_SUCCESS";
const GET_SALES_DROPDOWN_ERROR = "GET_SALES_DROPDOWN_ERROR";

const BUTTON_SELECT_STATUS_INIT = "BUTTON_SELECT_STATUS_INIT";
const BUTTON_SELECT_STATUS_SUCCESS = "BUTTON_SELECT_STATUS_SUCCESS";
const BUTTON_SELECT_STATUS_ERROR = "BUTTON_SELECT_STATUS_ERROR";

const DELETE_ACTIVE_STATUS_INIT = "DELETE_ACTIVE_STATUS_INIT";
const DELETE_ACTIVE_STATUS_SUCCESS = "DELETE_ACTIVE_STATUS_SUCCESS";
const DELETE_ACTIVE_STATUS_ERROR = "DELETE_ACTIVE_STATUS_ERROR";

const GET_SALES_TARGET_INIT = "GET_SALES_TARGET_INIT";
const GET_SALES_TARGET_SUCCESS = "GET_SALES_TARGET_SUCCESS";
const GET_SALES_TARGET_ERROR = "GET_SALES_TARGET_ERROR";

const IMPORT_CSV_FILE_INIT = "IMPORT_CSV_FILE_INIT";
const IMPORT_CSV_FILE_SUCCESS = "IMPORT_CSV_FILE_SUCCESS";
const IMPORT_CSV_FILE_ERROR = "IMPORT_CSV_FILE_ERROR";

const GET_SALES_TARGET_BY_ID_INIT = "GET_SALES_TARGET_BY_ID_INIT";
const GET_SALES_TARGET_BY_ID_SUCCESS = "GET_SALES_TARGET_BY_ID_SUCCESS";
const GET_SALES_TARGET_BY_ID_ERROR = "GET_SALES_TARGET_BY_ID_ERROR";

// Authentication
const LOGIN_AUTHENTICATION_INIT = "LOGIN_AUTHENTICATION_INIT";
const LOGIN_AUTHENTICATION_SUCCESS = "LOGIN_AUTHENTICATION_SUCCESS";
const LOGIN_AUTHENTICATION_ERROR = "LOGIN_AUTHENTICATION_ERROR";

// Hr Candidacy
const GET_HR_CANDIDACY_INIT = "GET_HR_CANDIDACY_INIT";
const GET_HR_CANDIDACY_SUCCESS = "GET_HR_CANDIDACY_SUCCESS";
const GET_HR_CANDIDACY_ERROR = "GET_HR_CANDIDACY_ERROR";

const GET_HR_CANDIDACY_BY_ID_INIT = "GET_HR_CANDIDACY_BY_ID_INIT";
const GET_HR_CANDIDACY_BY_ID_SUCCESS = "GET_HR_CANDIDACY_BY_ID_SUCCESS";
const GET_HR_CANDIDACY_BY_ID_ERROR = "GET_HR_CANDIDACY_BY_ID_ERROR";

const ADD_HR_CANDIDACY_INIT = "ADD_HR_CANDIDACY_INIT";
const ADD_HR_CANDIDACY_SUCCESS = "ADD_HR_CANDIDACY_SUCCESS";
const ADD_HR_CANDIDACY_ERROR = "ADD_HR_CANDIDACY_ERROR";

const EDIT_HR_CANDIDACY_INIT = "EDIT_HR_CANDIDACY_INIT";
const EDIT_HR_CANDIDACY_SUCCESS = "EDIT_HR_CANDIDACY_SUCCESS";
const EDIT_HR_CANDIDACY_ERROR = "EDIT_HR_CANDIDACY_ERROR";

const EDIT_HR_CANDIDACY_STATUS_INIT = "EDIT_HR_CANDIDACY_STATUS_INIT";
const EDIT_HR_CANDIDACY_STATUS_SUCCESS = "EDIT_HR_CANDIDACY_STATUS_SUCCESS";
const EDIT_HR_CANDIDACY_STATUS_ERROR = "EDIT_HR_CANDIDACY_STATUS_ERROR";

export {
  GET_USERS_DATA_INIT,
  GET_USERS_DATA_SUCCESS,
  GET_USERS_DATA_ERROR,

  GET_USERS_DEPARTMENTS_INIT,
  GET_USERS_DEPARTMENTS_SUCCESS,
  GET_USERS_DEPARTMENTS_ERROR,

  ADD_USERS_DATA_INIT,
  ADD_USERS_DATA_SUCCESS,
  ADD_USERS_DATA_ERROR,

  EDIT_USERS_INIT,
  EDIT_USERS_SUCCESS,
  EDIT_USERS_ERROR,

  GET_USERS_PERMISSION_INIT,
  GET_USERS_PERMISSION_SUCCESS,
  GET_USERS_PERMISSION_ERROR,

  UPDATE_USERS_INIT,
  UPDATE_USERS_SUCCESS,
  UPDATE_USERS_ERROR,

  // Department Module
  GET_DEPARTMENTS_INIT,
  GET_DEPARTMENTS_SUCCESS,
  GET_DEPARTMENTS_ERROR, 
  
  ADD_DEPARTMENTS_INIT,
  ADD_DEPARTMENTS_SUCCESS,
  ADD_DEPARTMENTS_ERROR,
  
  GET_DEPARTMENTS_BY_ID_INIT,
  GET_DEPARTMENTS_BY_ID_SUCCESS,
  GET_DEPARTMENTS_BY_ID_ERROR,

  EDIT_DEPARTMENTS_INIT,
  EDIT_DEPARTMENTS_SUCCESS,
  EDIT_DEPARTMENTS_ERROR,

// Performance Main Parameter
  GET_PERFORMANCE_INIT,
  GET_PERFORMANCE_SUCCESS,
  GET_PERFORMANCE_ERROR,

  ADD_PERFORMANCE_INIT,
  ADD_PERFORMANCE_SUCCESS,
  ADD_PERFORMANCE_ERROR,

  GET_PERFORMANCE_BY_ID_INIT,
  GET_PERFORMANCE_BY_ID_SUCCESS,
  GET_PERFORMANCE_BY_ID_ERROR,

  EDIT_PERFORMANCE_INIT,
  EDIT_PERFORMANCE_SUCCESS,
  EDIT_PERFORMANCE_ERROR,

// Sub Performance
  GET_SUBPERFORMANCE_INIT,
  GET_SUBPERFORMANCE_SUCCESS,
  GET_SUBPERFORMANCE_ERROR,

  ADD_SUBPERFORMANCE_INIT,
  ADD_SUBPERFORMANCE_SUCCESS,
  ADD_SUBPERFORMANCE_ERROR,

  GET_SUBPERFORMANCE_BY_ID_INIT,
  GET_SUBPERFORMANCE_BY_ID_SUCCESS,
  GET_SUBPERFORMANCE_BY_ID_ERROR,

  EDIT_SUBPERFORMANCE_INIT,
  EDIT_SUBPERFORMANCE_SUCCESS,
  EDIT_SUBPERFORMANCE_ERROR,

// Evaluation
  GET_CALCULATION_INIT,
  GET_CALCULATION_SUCCESS,
  GET_CALCULATION_ERROR,

  SAVE_CALCULATION_INIT,
  SAVE_CALCULATION_SUCCESS,
  SAVE_CALCULATION_ERROR,

// Mom Modules
  GET_MOM_INIT,
  GET_MOM_SUCCESS,
  GET_MOM_ERROR,

  SUBMIT_MOM_INIT,
  SUBMIT_MOM_SUCCESS,
  SUBMIT_MOM_ERROR,

  EDIT_MOM_DATA_INIT,
  EDIT_MOM_DATA_SUCCESS,
  EDIT_MOM_DATA_ERROR,

// Time Log
  ADD_CHECKIN_INIT,
  ADD_CHECKIN_SUCCESS,
  ADD_CHECKIN_ERROR,

  UPDATE_CHECKOUT_INIT,
  UPDATE_CHECKOUT_SUCCESS,
  UPDATE_CHECKOUT_ERROR,

  // Sales Module
  PROPOSAL_SUBMISSION_INIT,
  PROPOSAL_SUBMISSION_SUCCESS,
  PROPOSAL_SUBMISSION_ERROR,

  POST_PROPOSAL_SUBMIT_INIT,
  POST_PROPOSAL_SUBMIT_SUCCESS,
  POST_PROPOSAL_SUBMIT_ERROR,

  GET_PROPOSAL_BY_ID_INIT,
  GET_PROPOSAL_BY_ID_SUCCESS,
  GET_PROPOSAL_BY_ID_ERROR,
  
  UPLOAD_PROPOSAL_INIT,
  UPLOAD_PROPOSAL_SUCCESS,
  UPLOAD_PROPOSAL_ERROR,

  UPDATE_STATUS_INIT,
  UPDATE_STATUS_SUCCESS,
  UPDATE_STATUS_ERROR,

  GET_SALES_DROPDOWN_INIT,
  GET_SALES_DROPDOWN_SUCCESS,
  GET_SALES_DROPDOWN_ERROR,

  BUTTON_SELECT_STATUS_INIT,
  BUTTON_SELECT_STATUS_SUCCESS,
  BUTTON_SELECT_STATUS_ERROR,

  DELETE_ACTIVE_STATUS_INIT,
  DELETE_ACTIVE_STATUS_SUCCESS,
  DELETE_ACTIVE_STATUS_ERROR,

  GET_SALES_TARGET_INIT,
  GET_SALES_TARGET_SUCCESS,
  GET_SALES_TARGET_ERROR,

  IMPORT_CSV_FILE_INIT,
  IMPORT_CSV_FILE_SUCCESS,
  IMPORT_CSV_FILE_ERROR,

  GET_SALES_TARGET_BY_ID_INIT,
  GET_SALES_TARGET_BY_ID_SUCCESS,
  GET_SALES_TARGET_BY_ID_ERROR,

  // Authentication
  LOGIN_AUTHENTICATION_INIT,
  LOGIN_AUTHENTICATION_SUCCESS,
  LOGIN_AUTHENTICATION_ERROR,

  // Hr Candidacy
  GET_HR_CANDIDACY_INIT,
  GET_HR_CANDIDACY_SUCCESS,
  GET_HR_CANDIDACY_ERROR,

  GET_HR_CANDIDACY_BY_ID_INIT,
  GET_HR_CANDIDACY_BY_ID_SUCCESS,
  GET_HR_CANDIDACY_BY_ID_ERROR,

  ADD_HR_CANDIDACY_INIT,
  ADD_HR_CANDIDACY_SUCCESS,
  ADD_HR_CANDIDACY_ERROR,

  EDIT_HR_CANDIDACY_INIT,
  EDIT_HR_CANDIDACY_SUCCESS,
  EDIT_HR_CANDIDACY_ERROR,

  EDIT_HR_CANDIDACY_STATUS_INIT,
  EDIT_HR_CANDIDACY_STATUS_SUCCESS,
  EDIT_HR_CANDIDACY_STATUS_ERROR
};
